"""The mathematical core of Quantum Foundations Lab.

This package is the reference implementation (§2). It depends only on NumPy and
must stay independent of React, browser rendering, FastAPI, lesson copy and
animation timing, so that the frontend's TypeScript mathematics can be
validated against it.
"""

from .entanglement import (
    BELL_STATES,
    bell_phi_minus,
    bell_phi_plus,
    bell_psi_minus,
    bell_psi_plus,
    concurrence_two_qubit,
    density_matrix,
    is_product_state,
    partial_trace,
    purity,
    reduced_density_matrix,
    schmidt_coefficients,
)
from .gates import (
    CNOT,
    CZ,
    NAMED_GATES,
    PARAMETRIC_GATES,
    SDG,
    SWAP,
    TDG,
    H,
    I,
    S,
    T,
    X,
    Y,
    Z,
    apply_gate,
    controlled,
    gate_matrix,
    gate_qubit_count,
    is_unitary,
    phase,
    rx,
    ry,
    rz,
)
from .measurement import measure_computational, measure_qubit, sample_measurements
from .observables import (
    axis_from_angles,
    eigensystem,
    expectation_value,
    is_hermitian,
    projective_measurement_distribution,
    spin_observable,
    variance,
)
from .states import (
    angles_from_qubit,
    bloch_vector,
    equivalent_up_to_global_phase,
    global_phase_align,
    ket0,
    ket1,
    ket_minus,
    ket_minus_i,
    ket_plus,
    ket_plus_i,
    normalize_state,
    probabilities,
    qubit_from_angles,
    validate_state,
)
from .tensor import (
    basis_labels,
    computational_basis_state,
    reshape_state_for_subsystems,
    tensor_product,
)
from .types import (
    HERMITIAN_ATOL,
    MAX_CIRCUIT_DEPTH,
    MAX_QUBITS,
    MAX_SHOTS,
    NORMALIZATION_ATOL,
    PROBABILITY_ATOL,
    UNITARY_ATOL,
    ComplexMatrix,
    ComplexVector,
    MeasurementOutcome,
    QubitAngles,
    RealVector,
)
from .validation import QuantumValidationError

__all__ = [
    "BELL_STATES",
    "CNOT",
    "CZ",
    "ComplexMatrix",
    "ComplexVector",
    "H",
    "HERMITIAN_ATOL",
    "I",
    "MAX_CIRCUIT_DEPTH",
    "MAX_QUBITS",
    "MAX_SHOTS",
    "MeasurementOutcome",
    "NAMED_GATES",
    "NORMALIZATION_ATOL",
    "PARAMETRIC_GATES",
    "PROBABILITY_ATOL",
    "QuantumValidationError",
    "QubitAngles",
    "RealVector",
    "S",
    "SDG",
    "SWAP",
    "T",
    "TDG",
    "UNITARY_ATOL",
    "X",
    "Y",
    "Z",
    "angles_from_qubit",
    "apply_gate",
    "axis_from_angles",
    "basis_labels",
    "bell_phi_minus",
    "bell_phi_plus",
    "bell_psi_minus",
    "bell_psi_plus",
    "bloch_vector",
    "computational_basis_state",
    "concurrence_two_qubit",
    "controlled",
    "density_matrix",
    "eigensystem",
    "equivalent_up_to_global_phase",
    "expectation_value",
    "gate_matrix",
    "gate_qubit_count",
    "global_phase_align",
    "is_hermitian",
    "is_product_state",
    "is_unitary",
    "ket0",
    "ket1",
    "ket_minus",
    "ket_minus_i",
    "ket_plus",
    "ket_plus_i",
    "measure_computational",
    "measure_qubit",
    "normalize_state",
    "partial_trace",
    "phase",
    "probabilities",
    "projective_measurement_distribution",
    "purity",
    "qubit_from_angles",
    "reduced_density_matrix",
    "reshape_state_for_subsystems",
    "rx",
    "ry",
    "rz",
    "sample_measurements",
    "schmidt_coefficients",
    "spin_observable",
    "tensor_product",
    "validate_state",
    "variance",
]
